# Copyright (C) 2021 Toitware ApS. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be found in the LICENSE file.

# Specification file for the door checker Toit app.

name: Door checker
entrypoint: door-checker.toit
triggers:
  on_install: true
  on_boot: true
  on_interval: 60s
