# filename: light-detector.yaml

# Specification file for the light detector Toit app.
#
# Light detector is a simple Toit app, which measures the level of
# light in the room once a minute.

name: Light detector
entrypoint: light-detector.toit
triggers:
  on_install: true
  on_boot: true
  on_interval: 60s
