# Copyright (C) 2021 Toitware ApS. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be found in the LICENSE file.

# Specification file for the light detector Toit app.
#
# Light detector is a simple Toit app, which measures the level of
# light in the room once a minute.

name: Light detector
entrypoint: light-detector.toit
triggers:
  on_install: true
  on_boot: true
  on_interval: 60s
